/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import java.util.*

enum class TokenType(val priority: Int) {
    NUMBER(-1),
    PLUS(0),
    MINUS(0),
    MUL(10),
    DIV(10),
    PARENTHESES_OPEN(20),
    PARENTHESES_CLOSE(20)
}

data class Token(
    val type: TokenType,
    val value: String
)

fun parse(str: String): List<Token> {
    var i = 0
    val result = mutableListOf<Token>()

    while (i < str.length) {
        when (str[i]) {
            '+' -> result.add(Token(TokenType.PLUS, "+"))
            '-' -> result.add(Token(TokenType.MINUS, "-"))
            '*' -> result.add(Token(TokenType.MUL, "*"))
            '/' -> result.add(Token(TokenType.DIV, "/"))
            '(' -> result.add(Token(TokenType.PARENTHESES_OPEN, "("))
            ')' -> result.add(Token(TokenType.PARENTHESES_CLOSE, ")"))
            else -> {
                if (str[i].isWhitespace()) {
                    i++
                    continue
                }

                val start = i
                while (i < str.length && str[i].isDigit()) {
                    i++
                }
                result.add(Token(TokenType.NUMBER, str.substring(start, i)))
                continue
            }
        }
        i++
    }

    return result
}

fun eval(tokens: List<Token>): Int {
    return eval(tokens.toCollection(LinkedList()))
}

fun eval(tokens: LinkedList<Token>): Int {
    if (tokens.isEmpty()) {
        throw IllegalArgumentException("Empty tokens")
    }

    val bucket = LinkedList<Token>()

    while (tokens.isNotEmpty()) {
        val token = tokens.poll()

        // 5 + 5
        when (token.type) {
            TokenType.NUMBER -> {
                val nextOperator = tokens.peek()
                val lastOperator = bucket.peekLast()

                if (lastOperator == null) {
                    bucket.add(token)
                    continue
                }

                if (nextOperator != null && nextOperator.type.priority > lastOperator.type.priority) {
                    bucket.add(token)
                    continue
                }

                when (lastOperator.type) {
                    TokenType.PLUS, TokenType.MINUS, TokenType.MUL, TokenType.DIV -> {
                        bucket.pollLast() // remove last operator
                        val lastNumber = bucket.pollLast()
                        val calculatedResult = when (lastOperator.type) {
                            TokenType.PLUS -> (lastNumber.value.toInt() + token.value.toInt())
                            TokenType.MINUS -> (lastNumber.value.toInt() - token.value.toInt())
                            TokenType.MUL -> (lastNumber.value.toInt() * token.value.toInt())
                            TokenType.DIV -> (lastNumber.value.toInt() / token.value.toInt())
                            else -> throw IllegalArgumentException("Invalid operator")
                        }
                        val resultToken = Token(TokenType.NUMBER, calculatedResult.toString())
                        bucket.add(resultToken)
                    }

                    TokenType.PARENTHESES_OPEN -> {
                        bucket.add(token)
                    }

                    else -> {
                        // do nothing
                    }
                }
            }

            TokenType.PLUS, TokenType.MINUS, TokenType.MUL, TokenType.DIV, TokenType.PARENTHESES_OPEN -> {
                bucket.add(token)
            }

            TokenType.PARENTHESES_CLOSE -> {
                val bucketUntilOpenParentheses = LinkedList<Token>()
                while (bucket.isNotEmpty()) {
                    val last = bucket.pollLast()
                    if (last.type == TokenType.PARENTHESES_OPEN) {
                        break
                    }
                    bucketUntilOpenParentheses.addFirst(last)
                }
                val result = eval(bucketUntilOpenParentheses)
                val resultToken = Token(TokenType.NUMBER, result.toString())
                tokens.addFirst(resultToken)
            }
        }
    }

    if (bucket.size == 1) {
        return bucket.last.value.toInt()
    } else {
        return eval(bucket)
    }
}
